modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="mcaipet"
version="1.0.0"
displayName="MC AI Pet"
authors="bauerelizabeth07139"
description='''AI智能宠物，可控制多个虚拟玩家'''

[[dependencies.mcaipet]]
modId="forge"
mandatory=true
versionRange="[47.2.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.mcaipet]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[options]
guiCompatible=true
